/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  mySidebar: [
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'doc',
        id: 'introduction/introduction',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'introduction/overview',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'introduction/what-is-open-edge',
          label: 'What Is Open Edge'
        },
        {
          type: 'doc',
          id: 'introduction/why-open-edge',
          label: 'Why Open Edge'
        },
      ]
    },
    {
      type: 'category',
      label: 'Technology',
      link: {
        type: 'doc',
        id: 'technology/technology',
      },
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'technology/architecture',
          label: 'Architecture'
        },
        {
          type: 'doc',
          id: 'technology/work-proof',
          label: 'Work Proof'
        },
        {
          type: 'doc',
          id: 'technology/consensus',
          label: 'Consensus'
        },
        {
          type: 'doc',
          id: 'technology/peeredge',
          label: 'PeerEdge'
        },
      ]
    },
    {
      type: 'doc',
      id: 'network',
      label: 'Network',
    },
    {
      type: 'doc',
      id: 'user-guide',
      label: 'User Guide',
    },
    {
      type: 'doc',
      id: 'rewards',
      label: 'Rewards',
    },
    {
      type: 'doc',
      id: 'official-links',
      label: 'Official Links',
    },
   ]
};

export default sidebars;
